FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc pkg-config zlib1g-dev libxml2-dev libxslt1-dev libxmlsec1-dev libxmlsec1-openssl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --no-binary lxml,xmlsec -r requirements.txt

COPY . .

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
